[project]
name = "foreclosure-map"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "esridump>=1.13.0",
    "prefect>=3.4.19",
    "prefect-cloud>=0.1.8",
]
